name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - main

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps: # 步骤
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - name: test aa
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
#      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
#        uses: actions/setup-node@v1 # 作用：安装nodejs
#        with:
#          node-version: ${{ matrix.node-version }} # 版本



#      - name: stop script if command error
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.KEY }}
#          port: ${{ secrets.PORT }}
#          script_stop: true
#          script: |
#            mkdir abcd
#            ls -al

#成功03 ssh登录 拉取服务器上指定仓库 git pull
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@master
#        with:
#          host: 118.25.22.194
#          username: root
#          password: ${{ secrets.PASSWORD_118 }}
#          port: 22
#          script: |
#            pwd
#            cd /opt/test01
#            pwd
#            git pull
#            ls

# 成功01 ftp 远程同步文件（公司服务器可以，自己的服务器不行）
#      - name: Sync files # 步骤3 （只提交到github可以使用这个步骤）
#        uses: SamKirkland/FTP-Deploy-Action@4.0.1-patch # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
#        with:
#          server: 119.23.224.32
#          username: xiaosu
#          password: ${{ secrets.FTP_PASSWORD }}
#          local-dir: ./docs/
#          server-dir: /home/xiaosu/

# 成功02 ssh scp远程同步文件
#      - name: copy file via ssh password
#        uses: suxiaolong/scp-action@master
#        with:
#          host: 118.25.22.194
#          username: root
#          password: ${{ secrets.PASSWORD_118 }}
#          port: 22
#          source: "./docs/*"       # /home/xiaosu/docs
#          target: "/home/xiaosu"   # /root/test/88.txt










